### ISSUE TITLE
Reinstalling Istio Operator after deleting it is not succeeding because customresourcedefinitions.apiextensions.k8s.io "installations.istio.openshift.com" already exists

### ISSUE THREAD

**Issue by gbaufake** [maistra/openshift-ansible#3]
#### Description

Following the documentation provided on (https://github.com/Maistra/openshift-ansible/blob/maistra-0.1.0-ocp-3.1.0-istio-1.0.0/istio/Installation.md#installing-the-istio-operator), istio-operator installation is not sucedding because customresourcedefinitions.apiextensions.k8s.io "installations.istio.openshift.com" already exists

Command:

`oc new-app -f https://raw.githubusercontent.com/Maistra/openshift-ansible/maistra-0.1.0-ocp-3.1.0-istio-1.0.0/istio/istio_community_operator_template.yaml -p=OPENSHIFT_ISTIO_MASTER_PUBLIC_URL=https://url:8443`

Result:
> --> Deploying template "istio-operator/istio-removal-job" for "https://raw.githubusercontent.com/Maistra/openshift-ansible/maistra-0.1.0-ocp-3.1.0-istio-1.0.0/istio/istio_community_operator_template.yaml" to project istio-operator

     * With parameters:
        * Master Public URL=https://url:8443
        * OpenShift Release=v3.10.0
        * Istio Operator Namespace=istio-operator
        * Default Prefix=maistra/
        * Default Version=0.1.0
        * Default Deployment Type=origin
> --> Creating resources ...
    role "istio-operator" created
    rolebinding "default-account-istio-operator" created
    error: clusterrolebindings.rbac.authorization.k8s.io "default-account-istio-operator-cluster-role-binding" already exists
    deployment "istio-operator" created
    error:

**Comment by gbaufake** [comment]
It seems to be solved by including the following commands before the deploying:


`oc delete -f https://raw.githubusercontent.com/Maistra/istio-operator/maistra-0.1.0/deploy/crd.yaml --ignore-not-found=true`

`oc delete -f https://raw.githubusercontent.com/Maistra/istio-operator/maistra-0.1.0/deploy/rbac.yaml --ignore-not-found=true`

**Comment by gbaufake** [comment]
Copied to https://issues.jboss.org/projects/MAISTRA/issues/MAISTRA-4

**Comment by knrc** [comment]
Closing as it has been moved to the MAISTRA jira
