### ISSUE TITLE
Instructions for restarting openshift in Installation.md are outdated

### ISSUE THREAD

**Issue by jwendell** [maistra/openshift-ansible#35]
Instructions for restarting openshift in Installation.md are outdated:
- https://docs.openshift.com/container-platform/3.10/release_notes/ocp_3_10_release_notes.html#ocp-310-important-installation-changes
- https://docs.openshift.com/container-platform/3.10/release_notes/ocp_3_10_release_notes.html#ocp-310-notable-technical-changes

It's `master-restart` now

**Comment by knrc** [comment]
@jwendell Can you please open this in JIRA?  Thanks
