### ISSUE TITLE
openshift-ansible-istio-installer-job pod is not starting after unsuccessful installation

### ISSUE THREAD

**Issue by gbaufake** [maistra/openshift-ansible#4]
After a successful installation following #3 with workarounds, a second  openshift-ansible-istio-installer-job pod tries to start but with errors

Pod screenshots

![image](https://user-images.githubusercontent.com/2313749/44553865-50f97180-a705-11e8-8eb3-c07761161b2e.png)

![image](https://user-images.githubusercontent.com/2313749/44554128-222fcb00-a706-11e8-8e3b-2954da36d93e.png)

First log of openshift-ansible 
[cwwqq8.log](https://github.com/Maistra/openshift-ansible/files/2316381/cwwqq8.log)

**Comment by gbaufake** [comment]
Copied to https://issues.jboss.org/projects/MAISTRA/issues/MAISTRA-5

**Comment by knrc** [comment]
Note that the first installation failed, it did not succeed

**Comment by knrc** [comment]
Closing to move over to MAISTRA jira
