### ISSUE TITLE
Uninstall/reinstall fails

### ISSUE THREAD

**Issue by ptescher** [maistra/openshift-ansible#42]
Trying to upgrade (reinstall) from 0.2.0 to 0.3.0 I ran into a few issues:

1. The Istio CRDTs don't get removed properly, so the install fails when trying to create them.
2. The validating web hook doesn't get removed either.
3. Even when deleting the validating web hook manually it seems like it is being created twice, and the second time it causes the install to fail.

The only way I could get things installed is to manually delete everything:

```bash
oc delete -f https://raw.githubusercontent.com/Maistra/openshift-ansible/maistra-0.3/roles/openshift_istio/files/istio-crds.yaml -n istio-system
oc delete validatingwebhookconfigurations.admissionregistration.k8s.io/istio-galley -n istio-system
```

And then continue to delete the validating web hook during the installation.

**Comment by brian-avery** [comment]
@ptescher How are you trying to upgrade Istio? Istio should first be removed via the instructions here: http://maistra.io/docs/install/#_upgrading_from_a_pre_existing_installation before attempting to install the new version. The removal process should remove the webhook and CRDs.

**Comment by ptescher** [comment]
@brian-avery I removed by deleting the installation resource in istio-operator (so its more an uninstall bug than an upgrade bug).

**Comment by knrc** [comment]
The documentation asks you to remove older versions using their removal process, until 0.3.0 we did not expect upgrade to work but it should do so from 0.3.0 onwards.

The maistra documentation currently includes

> If there is an existing, pre-0.3.0 Istio istallation then the Istio Control Plane must be removed by the associated operator prior to installing the 0.3.0 Tech Preview

but also gives the manual instructions if this had not been done.

Did you remove the resource using the 0.2.0 operator or 0.3.0?  Could you attach the log from the removal?  Thanks very much

**Comment by ptescher** [comment]
After trying again a few times I could not reproduce this error, I assume something was not properly removed the first time I uninstalled. Closing this issue.
