### ISSUE TITLE
Invalid tech-preview kiali image tag 

### ISSUE THREAD

**Issue by siamaksade** [maistra/openshift-ansible#43]
The Kiali image tag in the examples and docs for tech-preview are incorrect and include an extra "v":
https://github.com/Maistra/openshift-ansible/blob/maistra-0.3/istio/cr-kiali.yaml#L10
https://docs.openshift.com/container-platform/3.11/servicemesh-install/servicemesh-install.html#creating-custom-resource

The default version is stated as 'v0.7.2' which is correct for community images but incorrect for tech-preview images. The tags in the Red Hat registry is '0.7.2', while in docker hub 'v0.7.2':

https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/openshift-istio-tech-preview/kiali
https://hub.docker.com/r/kiali/kiali/tags/

**Comment by knrc** [comment]
@siamaksade The prefix and version in that example are for the community images so should now be kiali/ and v0.8.1, I'll update it.

**Comment by knrc** [comment]
The version has now been updated to match the community version used in maistra 0.3.0

**Comment by siamaksade** [comment]
Super. The docs also needs an update:
https://docs.openshift.com/container-platform/3.11/servicemesh-install/servicemesh-install.html#creating-custom-resource

**Comment by knrc** [comment]
The PR to make that change was submitted a few days ago, we're still waiting for it to be merged.
